language: php
php:
    - 5.6
    - 5.5
    - 5.4
#    - hhvm

before_script:
    - composer selfupdate
    - composer install --prefer-source
#    - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo "hhvm.libxml.ext_entity_whitelist = file,http"  >> /etc/hhvm/php.ini; fi;'

script: ./vendor/bin/phpunit
