parameters:
    mcfedr_you_tube_live_streams.api_key: ''
    mcfedr_you_tube_live_streams.channel_id: ~

services:
    mcfedr_you_tube_live_streams.command.streams:
        class: Mcfedr\YouTube\LiveStreamsBundle\Command\YouTubeStreamsCommand
        arguments:
            - "@mcfedr_you_tube_live_streams.loader"
            - "%mcfedr_you_tube_live_streams.channel_id%"
        tags:
            -  { name: console.command }

    mcfedr_you_tube_live_streams.youtube_client:
        class: GuzzleHttp\Client
        factory: [Mcfedr\YouTube\LiveStreamsBundle\DependencyInjection\GuzzleClientFactory, get]
        arguments:
            -
                base_uri: "https://www.googleapis.com/youtube/v3/"
            - "%mcfedr_you_tube_live_streams.api_key%"
