services:
    mcfedr_you_tube_live_streams.loader:
        class: mcfedr\YouTube\LiveStreamsBundle\Streams\YouTubeStreamLoader
        arguments:
            - "@mcfedr_you_tube_live_streams.youtube_client"
            - "%mcfedr_you_tube_live_streams.channel_id%"
            - "%kernel.cache_dir%"
            - "@logger"

    mcfedr_you_tube_live_streams.youtube_client:
        class: Guzzle\Http\Client
        arguments:
            - "https://www.googleapis.com/youtube/{version}/"
            -
                version: "v3"
                request.options:
                    query:
                        key: "%mcfedr_you_tube_live_streams.api_key%"
        calls:
            - [addSubscriber, ["@mcfedr_you_tube_live_streams.youtube_log_plugin"]]

    mcfedr_you_tube_live_streams.youtube_log_adapter:
        class: Guzzle\Log\PsrLogAdapter
        arguments: ["@logger"]

    mcfedr_you_tube_live_streams.youtube_log_plugin:
        class: Guzzle\Plugin\Log\LogPlugin
        arguments: ["@mcfedr_you_tube_live_streams.youtube_log_adapter", ">>>>>>>>\n{request}\n<<<<<<<<\n{response}\n--------\n{curl_stderr}"]
