services:
    mcfedr_you_tube_live_streams.streams:
        class: Guzzle\Http\Message\Response
        factory_class: Guzzle\Http\StaticClient
        factory_method: get
        arguments:
            - "https://www.googleapis.com/youtube/v3/search"
            -
                plugins:
                    - "@mcfedr_you_tube_live_streams.youtube_log_plugin"
                query:
                    key: "%mcfedr_you_tube_live_streams.api_key%"
                    part: "snippet"
                    channelId: "%mcfedr_you_tube_live_streams.channel_id%"
                    eventType: "live"
                    type: "video"

    mcfedr_you_tube_live_streams.youtube_log_adapter:
        class: Guzzle\Log\PsrLogAdapter
        arguments: ["@logger"]

    mcfedr_you_tube_live_streams.youtube_log_plugin:
        class: Guzzle\Plugin\Log\LogPlugin
        arguments: ["@mcfedr_you_tube_live_streams.youtube_log_adapter", ">>>>>>>>\n{request}\n<<<<<<<<\n{response}\n--------\n{curl_stderr}"]
